[package]
name = "quinn-boring"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/quinn-rs/quinn-boring"
description = "BoringSSL crypto provider for quinn"
keywords = ["quic"]
categories = ["network-programming", "asynchronous"]
edition = "2021"
rust-version = "1.59"

[dependencies]
